/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import modelo.Persona;

/**
 * @author Natalia Salazar
 * @author Sebastián Arriagada
 * @author Luciano Castañeda
 * @author Julián Iturra
 */
public class Menu extends javax.swing.JFrame {

    //Atributos clase
    private Tabla t = new Tabla();

    public Menu() {
        initComponents();
    }

    public Persona cargarPersona() {

        Persona p = new Persona(this.nombre.getText(), Integer.parseInt(this.edad.getText()), this.apellido.getText(), this.correo.getText(), this.hora.getText(), this.asistencia.getText());
        this.nombre.setText("");
        this.edad.setText("");
        this.apellido.setText("");
        this.correo.setText("");
        this.hora.setText("");
        this.asistencia.setText("");

        return p;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNombre = new javax.swing.JLabel();
        eApellido = new javax.swing.JLabel();
        eEdad = new javax.swing.JLabel();
        eCorreo = new javax.swing.JLabel();
        eHora = new javax.swing.JLabel();
        eAsistencia = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        edad = new javax.swing.JTextField();
        agregarBTN = new javax.swing.JButton();
        apellido = new javax.swing.JTextField();
        correo = new javax.swing.JTextField();
        hora = new javax.swing.JTextField();
        eRegister = new javax.swing.JLabel();
        easyr = new javax.swing.JLabel();
        cancelarBTN = new javax.swing.JButton();
        asistencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eNombre.setForeground(new java.awt.Color(255, 255, 255));
        eNombre.setText("Nombre");
        getContentPane().add(eNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 142, -1, -1));

        eApellido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eApellido.setForeground(new java.awt.Color(255, 255, 255));
        eApellido.setText("Apellido");
        getContentPane().add(eApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 195, -1, -1));

        eEdad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eEdad.setForeground(new java.awt.Color(255, 255, 255));
        eEdad.setText("Edad");
        getContentPane().add(eEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 238, -1, -1));

        eCorreo.setBackground(new java.awt.Color(255, 255, 255));
        eCorreo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eCorreo.setForeground(new java.awt.Color(255, 255, 255));
        eCorreo.setText("Correo");
        getContentPane().add(eCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 284, -1, -1));

        eHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eHora.setForeground(new java.awt.Color(255, 255, 255));
        eHora.setText("Hora Llegada");
        getContentPane().add(eHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 336, -1, -1));

        eAsistencia.setBackground(new java.awt.Color(255, 255, 255));
        eAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        eAsistencia.setText("Asistencia");
        getContentPane().add(eAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 382, -1, -1));

        nombre.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 139, 228, -1));

        edad.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 235, 228, -1));

        agregarBTN.setText("Agregar");
        agregarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(agregarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 90, -1));

        apellido.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 189, 228, -1));

        correo.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 281, 228, -1));

        hora.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 333, 228, -1));

        eRegister.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        eRegister.setForeground(new java.awt.Color(255, 255, 255));
        eRegister.setText("REGISTRO DE ASISTENCIA");
        getContentPane().add(eRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 290, 70));

        easyr.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        easyr.setForeground(new java.awt.Color(255, 255, 255));
        easyr.setText("@EasyR");
        getContentPane().add(easyr, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 60, 30));

        cancelarBTN.setText("Cancelar");
        cancelarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBTNActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 90, -1));

        asistencia.setBackground(new java.awt.Color(255, 255, 255));
        asistencia.setToolTipText("");
        getContentPane().add(asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 379, 228, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese: \"Presente\" o \"Ausente\"");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 407, 228, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ejemplo: XXXXXXX@XXXXmail.cl");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 305, 228, 22));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ejemplo: XX:XX");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 357, 228, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ejemplo: XX");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 253, 228, 30));

        fondoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/colores-difuminados.jpg"))); // NOI18N
        fondoMenu.setText("jLabel5");
        getContentPane().add(fondoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBTNActionPerformed
        t.llenarTabla(cargarPersona());
        t.setVisible(true);
    }//GEN-LAST:event_agregarBTNActionPerformed

    private void cancelarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelarBTNActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarBTN;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextField asistencia;
    private javax.swing.JButton cancelarBTN;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel eApellido;
    private javax.swing.JLabel eAsistencia;
    private javax.swing.JLabel eCorreo;
    private javax.swing.JLabel eEdad;
    private javax.swing.JLabel eHora;
    private javax.swing.JLabel eNombre;
    private javax.swing.JLabel eRegister;
    private javax.swing.JLabel easyr;
    private javax.swing.JTextField edad;
    private javax.swing.JLabel fondoMenu;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
