/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Persona;

/**
 * @author Natalia Salazar
 * @author Sebastián Arriagada
 * @author Luciano Castañeda
 * @author Julián Iturra
 */
public class Tabla extends javax.swing.JFrame {

    //Atributos clase Table
    private DefaultTableModel dfTable;
    private Object[] o = new Object[6];
    private ArrayList<Persona> personas;

    /**
     * Creates new form Tabla
     */
    public Tabla() {
        initComponents();
        personas = new ArrayList();
        dfTable = new DefaultTableModel();
        dfTable.addColumn("Nombre");
        dfTable.addColumn("Edad");
        dfTable.addColumn("Apellido");
        dfTable.addColumn("Correo");
        dfTable.addColumn("Hora");
        dfTable.addColumn("Asistencia");
        this.table.setModel(dfTable);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }

    public void llenarTabla(Persona p) {
        this.personas.add(p);
        o[0] = p.getNombre();
        o[1] = p.getEdad();
        o[2] = p.getApellido();
        o[3] = p.getCorreo();
        o[4] = p.getHora();
        o[5] = p.getAsistencia();
        dfTable.addRow(o);
    }

    public void eliminarPersona() {
        int fila = this.table.getSelectedRow();
        if (fila >= 0) {
            this.personas.remove(fila);
            dfTable.removeRow(fila);
        }
    }

    public void ordenar() {
        table.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        eliminarBTN = new javax.swing.JButton();
        indicacionTF = new javax.swing.JLabel();
        ordenarBTN = new javax.swing.JButton();
        eliminartodoBTN = new javax.swing.JButton();
        indicacion2TF = new javax.swing.JLabel();
        fondoTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setBackground(new java.awt.Color(153, 255, 255));
        table.setForeground(new java.awt.Color(0, 0, 0));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 760, 280));

        eliminarBTN.setText("Eliminar Fila Seleccionada");
        eliminarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        indicacionTF.setBackground(new java.awt.Color(255, 255, 255));
        indicacionTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        indicacionTF.setForeground(new java.awt.Color(255, 255, 255));
        indicacionTF.setText("*Para editar haga doble click en el dato que desee editar");
        jPanel1.add(indicacionTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 390, 30));

        ordenarBTN.setText("Ordenar");
        ordenarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ordenarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        eliminartodoBTN.setText("Eliminar Todo");
        eliminartodoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminartodoBTNActionPerformed(evt);
            }
        });
        jPanel1.add(eliminartodoBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 120, 20));

        indicacion2TF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        indicacion2TF.setForeground(new java.awt.Color(255, 255, 255));
        indicacion2TF.setText("*Para ordenar, dar clic en el botón y luego dar clic en el encabezado que desee ordenar");
        jPanel1.add(indicacion2TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 590, 30));

        fondoTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondos/6cf01be6-magic.png"))); // NOI18N
        fondoTabla.setText("jLabel1");
        jPanel1.add(fondoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBTNActionPerformed
        eliminarPersona();
    }//GEN-LAST:event_eliminarBTNActionPerformed

    private void ordenarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarBTNActionPerformed
        ordenar();
    }//GEN-LAST:event_ordenarBTNActionPerformed

    private void eliminartodoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminartodoBTNActionPerformed

        // TODO add your handling code here:
        int fila = table.getRowCount();
        for (int i = fila - 1; i >= 0; i--) {
            dfTable.removeRow(i);
        }
    }//GEN-LAST:event_eliminartodoBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarBTN;
    private javax.swing.JButton eliminartodoBTN;
    private javax.swing.JLabel fondoTabla;
    private javax.swing.JLabel indicacion2TF;
    private javax.swing.JLabel indicacionTF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ordenarBTN;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
